name: Lint and test with coverage

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  lint-and-test-with-coverage:
    uses: inclusive-design/workflows/.github/workflows/node-pnpm-lint-and-test-with-coverage.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
